### ISSUE TITLE
what is the different between BiBloSAN and this project

### ISSUE THREAD

**Issue by loveJasmine** [taoshen58/DiSAN#1]

**Comment by taoshen58** [comment]
DiSAN and BiBloSAN are two models from the papers, *"DiSAN: Directional Self-Attention Network for RNN/CNN-free Language Understanding"* and *"Bi-Directional Block Self-Attention for Fast and Memory-Efficient Sequence Modeling"*, respectively. In addition, the DiSAN is the basis of BiBloSAN.

**Comment by loveJasmine** [comment]
so literally, DiSAN + block = BiBloSAN
