### ISSUE TITLE
word embedding

### ISSUE THREAD

**Issue by MariamEssam** [taoshen58/DiSAN#10]
Hello Tao,
Thank you for sharing your nice code. I need to test other word embeddings on your model, the new word embeddings have a different dimension, not 300. From what I get from the paper we will need to change the following configuration --word_embedding_length and --hidden_units_num to the new dimension. Is that correct? 
Thank you in advance

**Comment by aimiyu** [comment]
I think you need to change --word_embedding_length to the dimension of your new embeddings， as for the --hidden_units_num， you can set it to whatever you want to try.  There's a fcn layer converting input embedding of size --word_embedding_length to the hidden states of size  --hidden_units_num

**Comment by taoshen58** [comment]
@aimiyu Thanks for your answering, and you are correct.

**Comment by MariamEssam** [comment]
Gotcha! Thanks for replying. I wonder if there any relation between these two parameters or not? I  now understand it is independent parameter but is there any best practice i.e. if I have 50d do I still need to have 300 hidden layers or they should be less and Vice versa.

**Comment by taoshen58** [comment]
Actually, I don’t know any dependence between them. I’m  just accustomed to follow previous work’s settings
