### ISSUE TITLE
SST data process

### ISSUE THREAD

**Issue by SummmerSnow** [taoshen58/DiSAN#3]
Hi，
Thanks for your great work and your nice code;
I just can't figure why you use STree.txt and SOStr.txt when process the STS datasets?
why not just use dictionary.txt and sentiment_label.txt ?

**Comment by taoshen58** [comment]
Hi, 

Thanks for your interests.

The reason is that I once tested the recursive neural model in the project and I kept those module. Therefore, the files to indicate the parsing tree results were needed.
