### ISSUE TITLE
question about config parameter "only_sentence"

### ISSUE THREAD

**Issue by fred2008** [taoshen58/DiSAN#4]
hi, @taoshen58 

Thank you for sharing the code.

I am try to run the Disan on SST dataset as your paper does. I am confusing about the parameter  "only_sentence". As far as I know, if it is false as default setting in your code, the sentence phrases is included for training but not include for evaluating.

If I just want to reproduce your performance in your paper, it is correct to just set only_sentence to True ?

**Comment by taoshen58** [comment]
Hi, 

As you said, if "only_sentence" is set to False, the phrase-level samples will be in consideration during training, whereas if it's set to True, the only sentence-level samples will be used during the training. Under any circumstance, the evaluation only is applied to the sentence during test phrase.

**Comment by fred2008** [comment]
Hi, @taoshen58 

Thank you for your reply.

Could you tell me which setting is do you use when doing experiments ? Is it the default one: False ?

**Comment by taoshen58** [comment]
Yes, set the 'only_sentence' to false. And the evaluation provided in this paper is only the "fine-grained" and "root" shown in Table 1 of [RNTN](https://nlp.stanford.edu/~socherr/EMNLP2013_RNTN.pdf).

And, it is also confusing to me that, it seems they (e.g., RNTN, TreeLSTM) used the fine-grained and phrase&sentence-level label for training and made the evaluation on various settings (e.g., the four settings shown in table 1 aforementioned). Please refer to [here](https://github.com/tensorflow/fold/blob/master/tensorflow_fold/g3doc/sentiment.ipynb).

Welcome to discuss!
