### ISSUE TITLE
The net seems use lstm

### ISSUE THREAD

**Issue by lidra** [taoshen58/DiSAN#8]
Hi, I am very glad you share your code and you are so nice. The paper says the DiSAN can achieve state-of-the-art inference quality without any rnn and cnn, but in the code, 'contextual_bi_rnn' is a RNN net. So the best performance is got with the help of LSTM?
Thanks very much

**Comment by taoshen58** [comment]
Hi, it’s baseline method.

**Comment by lidra** [comment]
Oh, I am sorry. I got it.
