### ISSUE TITLE
About the structure of the code

### ISSUE THREAD

**Issue by lidra** [taoshen58/DiSAN#9]
Hi, When I try to run the test code, I found some errors of 'import' part in 'SNLI_disan/src/model/model_disan' because of the wrong path. So I must change the import code in order to run the code successfully. If the author can restructure the code or change the import code, it will be easier to run the code.
Thanks very much!

**Comment by taoshen58** [comment]
Hi, lidra, 

When I run the code in both IDE and Terminal, I did not witness this problem. Could you detail you running env and the settings?
